Skillberto\SonataExtendedAdminBundle\Entity\Base:
  type: mappedSuperclass
  repositoryClass: Skillberto\SonataExtendedAdminBundle\Entity\Repository\BaseRepository
  fields:
    active:
      type: boolean
    createdAt:
      type: datetime
    updatedAt:
      type: datetime
  lifecycleCallbacks:
    prePersist: [ createdAt ]
    postPersist: [ updateAt ]